'1'# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: '2')
Country.destroy_all
State.destroy_all
StudentClass.destroy_all
MemberStatus.destroy_all
Member.destroy_all
SponsorType.destroy_all
Sponsor.destroy_all
EventStatus.destroy_all
EventType.destroy_all
Event.destroy_all
MemberCheckIn.destroy_all
OfficerStatus.destroy_all
OfficerPosition.destroy_all
Officer.destroy_all
OfficerCheckIn.destroy_all
CoordinatorStatus.destroy_all
CoordinatorPosition.destroy_all
Coordinator.destroy_all
CoordinatorCheckIn.destroy_all
#Country Table
Country.create(name: “United States”, country_abbreviation: “US”)
Country.create(name: “Canada”, country_abbreviation: “CA”)
#State Table
State.create(country_id: ‘1’, name: “Washington”, state_abbreviation: “WA”)
State.create(country_id: ‘1’, name: “California”, state_abbreviation: “CA”)
State.create(country_id: ‘1’, name: “Georgia”, state_abbreviation: “GA”)
State.create(country_id: ‘2’, name: “Alberta”, state_abbreviation: “AB”)
State.create(country_id: ‘2’, name: “British Columbia”, state_abbreviation: “BC”)
State.create(country_id: ‘1’, name: “Connecticut”, state_abbreviation: “CT”)
State.create(country_id: ‘2’, name: “Manitoba”, state_abbreviation: “MB”)
State.create(country_id: ‘1’, name: “Indiana”, state_abbreviation: “IN”)
State.create(country_id: ‘1’, name: “Iowa”, state_abbreviation: “IA”)
State.create(country_id: ‘1’, name: “Texas”, state_abbreviation: “TX”)
State.create(country_id: ‘1’, name: “Arizona”, state_abbreviation: “AZ”)
State.create(country_id: ‘2’, name: “Prince Edward Island”, state_abbreviation: “PE”)
State.create(country_id: ‘1’, name: “Kentucky”, state_abbreviation: “KY”)
State.create(country_id: ‘1’, name: “Kansas”, state_abbreviation: “KS”)
State.create(country_id: ‘2’, name: “Quebec”, state_abbreviation: “QC”)
State.create(country_id: ‘1’, name: “Nevada”, state_abbreviation: “NV”)
State.create(country_id: ‘2’, name: “Saskatchewan”, state_abbreviation: “SK”)
State.create(country_id: ‘1’, name: “Pennsylvania”, state_abbreviation: “PA”)
State.create(country_id: ‘1’, name: “New Mexico”, state_abbreviation: “NM”)
State.create(country_id: ‘1’, name: “Minnesota”, state_abbreviation: “MN”)
State.create(country_id: ‘1’, name: “Michigan”, state_abbreviation: “MI”)
State.create(country_id: ‘1’, name: “Ohio”, state_abbreviation: “OH”)
State.create(country_id: ‘1’, name: “Tennessee”, state_abbreviation: “TN”)
State.create(country_id: ‘1’, name: “New York”, state_abbreviation: “NY”)
State.create(country_id: ‘2’, name: “Yukon”, state_abbreviation: “YT”)
#Student_Class Table
StudentClass.create(Student_class: “Freshman”, description: “A first Year Student”)
StudentClass.create(Student_class: “Sophomore”, description: “A Second Year Student”)
StudentClass.create(student_class: “Junior”, description: “A Third Year Student”)
StudentClass.create(student_class: “Senior”, description: “A Fourth Year Student”)
#Member_Status Table
MemberStatus.create(status: “Active”, description: “This is an active member”)
MemberStatus.create(status: “Inactive”, description: “This is an inactive member”)
#Member Table
Member.create(peoplesoft_id: '1202934', first_name: 'Josh', middle_initial: 'A', last_name: 'Smith', date_of_birth: '1998-02-22',  address: '4323 Quaker Oats', city: 'Houston', zip: '23422', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '83245629348', officer_status_id: '1', payment: 'true', student_class_id: '1', major: 'CIS')

#sponsor_type Table
SponsorType.create(sponsor_type: "Oil and Gas", description: "Companies that are in the oil and gas field area")
SponsorType.create(sponsor_type: "Consulting", description: "Companies that are in the consulting field area")
SponsorType.create(sponsor_type: "Electricity", description: "Companies that are in the electricity field area")
SponsorType.create(sponsor_type: "Technology", description: "Companies that are in the technology field area")
#Sponsor
Sponsor.create(company: "Shell", first_name: "Josh", last_name: "Smith", home_phone: "281-839-2333", mobile_phone: "832-881-4824", sponsor_type_id: '1')
Sponsor.create(company: "Exxon", first_name: "Robert", last_name: "Costales", home_phone: "331-924-2341", mobile_phone: "434-423-9432", sponsor_type_id: '1')
Sponsor.create(company: "Reynolds & Reynolds", first_name: "Layla", last_name: "Reese", home_phone: "281-553-5325", mobile_phone: "832-831-4714", sponsor_type_id: '2')
Sponsor.create(company: "HP", first_name: "Shang", last_name: "Wei", home_phone: "281-112-4532", mobile_phone: "832-131-4842", sponsor_type_id: '4')
Sponsor.create(company: "Chevron", first_name: "Becky", last_name: "Black", home_phone: "281-199-2293", mobile_phone: "832-402-0049", sponsor_type_id: '1')
Sponsor.create(company: "Reliant Energy", first_name: "Steve", last_name: "Ortega", home_phone: "281-491-3920", mobile_phone: "832-111-4804", sponsor_type_id: '3')
Sponsor.create(company: "Microsoft", first_name: "Angela", last_name: "Fling", home_phone: "221-209-4523", mobile_phone: "832-609-4815", sponsor_type_id: '4')
Sponsor.create(company: "TXU Energy", first_name: "Richard", last_name: "Dold", home_phone: "281-800-2573", mobile_phone: "832-612-1514", sponsor_type_id: '3')
Sponsor.create(company: "Accenture", first_name: "John", last_name: "Medina", home_phone: "281-989-2113", mobile_phone: "832-617-4592", sponsor_type_id: '2')
Sponsor.create(company: "Bain & Company", first_name: "Anthony", last_name: "Mekhail", home_phone: "281-129-2050", mobile_phone: "832-831-8230", sponsor_type_id: '2')
Sponsor.create(company: "Apple", first_name: "Andrew", last_name: "Ewing", home_phone: "281-109-2000", mobile_phone: "832-901-9034", sponsor_type_id: '4')
Sponsor.create(company: "IBM", first_name: "Katie", last_name: "Clark", home_phone: "281-819-2940", mobile_phone: "832-431-9280", sponsor_type_id: '4')
Sponsor.create(company: "Texaco", first_name: "Alyssa", last_name: "Jade", home_phone: "281-194-2850", mobile_phone: "832-849-4829", sponsor_type_id: '1')
Sponsor.create(company: "Samsung", first_name: "Colton", last_name: "Larp", home_phone: "281-029-9033", mobile_phone: "832-801-4928", sponsor_type_id: '4')
Sponsor.create(company: "Facebook", first_name: "Elaine", last_name: "Ta", home_phone: "281-490-2003", mobile_phone: "832-191-4284", sponsor_type_id: '4')
Sponsor.create(company: "Boston Consulting Group", first_name: "Ronald", last_name: "Oviedo", home_phone: "281-809-4333", mobile_phone: "832-381-1844", sponsor_type_id: '2')
Sponsor.create(company: "Deloitte", first_name: "Braden", last_name: "Kosher", home_phone: "281-839-2423", mobile_phone: "832-981-4390", sponsor_type_id: '2')
Sponsor.create(company: "Lukoil", first_name: "Alexander", last_name: "Mond", home_phone: "281-919-2303", mobile_phone: "832-850-4800", sponsor_type_id: '1')
Sponsor.create(company: "Total", first_name: "Sidney", last_name: "Deblanc", home_phone: "281-592-0333", mobile_phone: "832-681-4584", sponsor_type_id: '1')
Sponsor.create(company: "Intel", first_name: "Blake", last_name: "Griffin", home_phone: "281-849-0385", mobile_phone: "832-884-8103", sponsor_type_id: '4')
Sponsor.create(company: "KPMG", first_name: "Cody", last_name: "Vong", home_phone: "281-801-0433", mobile_phone: "832-190-4904", sponsor_type_id: '2')
Sponsor.create(company: "Mercer", first_name: "Morgan", last_name: "Prak", home_phone: "281-894-1893", mobile_phone: "832-194-0591", sponsor_type_id: '2')
Sponsor.create(company: "Spark Energy", first_name: "Veronica", last_name: "Lamone", home_phone: "281-809-2033", mobile_phone: "832-094-4514", sponsor_type_id: '3')
Sponsor.create(company: "Solarplicity", first_name: "Brandon", last_name: "Tep", home_phone: "281-1943", mobile_phone: "832-081-4856", sponsor_type_id: '3')
Sponsor.create(company: "Cirro Energy", first_name: "Travis", last_name: "Tran", home_phone: "281-019-9533", mobile_phone: "832-941-4004", sponsor_type_id: '3')
#Event_Status Table
EventStatus.create(status: "In Progress", description: "Event is in progress")
EventStatus.create(status: "Planned", description: "Event is planned")
EventStatus.create(status: "Cancelled", description: "Event was cancelled")
EventStatus.create(status: "Completed", description: "Event was completed")
#Event_Type Table
EventType.create(event_type: "Fundraiser", description: "Helps raise money for Association")
EventType.create(event_type: "Meeting", description: "Brings professionals to University to talk to students")
EventType.create(event_type: "Tutoring", description: "Help students with class homework")
EventType.create(event_type: "Open Discussion", description: "To discuss events such as voting for new board members")
EventType.create(event_type: "Competition", description: "Competition for students")
EventType.create(event_type: "Workshop", description: "Workshops to help students")
#Event Table
Event.create(description: "AITP General Meeting", event_date: "08/29/2019", event_type_id: '2', event_status_id: '4', sponsor_id: '1', fee: '', address: 156 Golf View Pass, building_name: "T1", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
Event.create(description: "AITP Career Help Session", event_date: "09/05/2019", event_type_id: '2', event_status_id: '4', sponsor_id: '2', fee: '', address: 3476 Dorton Crossing, building_name: "T2", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
Event.create(description: "AITP Resume Workshop", event_date: "09/20/2019", event_type_id: '1', event_status_id: '4', sponsor_id: '4', fee: '', address: 156 Golf View Pass, building_name: "T2", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
Event.create(description: "AITP Officers Meeting", event_date: "09/30/2019", event_type_id: '3', event_status_id: '4', sponsor_id: '3', fee: '', address: 5510 Sunny Valley Ln, building_name: "A2", city: "Houston", zip: 77048, state_id: '10', country_id: '1')
Event.create(description: "AITP General Meeting", event_date: "10/10/2019", event_type_id: '2', event_status_id: '4', sponsor_id: '4', fee: '', address: 555 University Lane, building_name: "B2", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
Event.create(description: "AITP Cat's Back Booth", event_date: "04/02/2020", event_type_id: '2', event_status_id: '1', sponsor_id: '2', fee: '', address: 555 University Lane, building_name: "B2", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
Event.create(description: "AITP Tutoring Session", event_date: "04/09/2020", event_type_id: 2, event_status_id: 1, sponsor_id: '3', fee: '', address: 555 University Lane, building_name: "B2", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
Event.create(description: "AITP General Meeting", event_date: "05/01/2020", event_type_id: 2, event_status_id: 3, sponsor_id: 4, fee: '', address: 555 University Lane, building_name: "B2", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
Event.create(description: "AITP Fundraising Event", event_date: "04/15/2020", event_type_id: 1, event_status_id: 2, sponsor_id: 1, fee: '', address: 134 Technology Rd, building_name: "X2", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
Event.create(description: "AITP Officers Meeting", event_date: "02/14/2020", event_type_id: 3, event_status_id: 4, sponsor_id: 1, fee: '', address: 555 University Lane, building_name: "C2", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
Event.create(description: "AITP General Meeting", event_date: "02/21/2020", event_type_id: 2, event_status_id: 4, sponsor_id: 2, fee: '', address: 555 University Lane, building_name: "B2", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
Event.create(description: "AITP Resume Workshop", event_date: "02/14/2020", event_type_id: 2, event_status_id: 3, sponsor_id: 4, fee: '', address: 555 University Lane, building_name: "B2", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
Event.create(description: "AITP Competition", event_date: "02/28/2020", event_type_id: 2, event_status_id: 4, sponsor_id: 3, fee: '', address: 555 University Lane, building_name: "B2", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
Event.create(description: "AITP General Meeting", event_date: "05/07/2020", event_type_id: 3, event_status_id: 4, sponsor_id: 1, fee: '', address: 555 University Lane, building_name: "B2", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
Event.create(description: "AITP General Meeting", event_date: "03/28/2020", event_type_id: 2, event_status_id: 3, sponsor_id: 2, fee: '', address: 555 University Lane, building_name: "A2", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
Event.create(description: "AITP Coordinators Meeting", event_date: "03/20/2020", event_type_id: 2, event_status_id: 3, sponsor_id: 4, fee: '', address: 555 University Lane, building_name: "T1", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
Event.create(description: "AITP General Meeting", event_date: "03/01/2020", event_type_id: 1, event_status_id: 4, sponsor_id: 2, fee: '', address: 735 Research Forest, building_name: "R2", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
Event.create(description: "AITP General Meeting", event_date: "01/12/2020", event_type_id: 2, event_status_id: 4, sponsor_id: 3, fee: '', address: 555 University Lane, building_name: "C3", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
Event.create(description: "AITP Fundraising Event", event_date: "04/08/2020", event_type_id: 2, event_status_id: 2, sponsor_id: 3, fee: '', address: 555 University Lane, building_name: "A4", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
Event.create(description: "AITP General Meeting", event_date: "04/25/2020", event_type_id: 4, event_status_id: 3, sponsor_id: 4, fee: '', address: 123 Misty Road, building_name: "W2", city: "Waco", zip: 77189, state_id: '10', country_id: '1')
Event.create(description: "AITP General Meeting", event_date: "03/10/2020", event_type_id: 2, event_status_id: 4, sponsor_id: 4, fee: '', address: 555 University Lane, building_name: "A2", city: "Houston", zip: 77004, state_id: '10', country_id: '1')
#Member_Check_In Table
MemberCheckIn.create( member_id: '2', event_id: '3', check_in_date: '2020-01-07 12:31')
MemberCheckIn.create( member_id: '4', event_id: '2', check_in_date: '2020-02-20 02:03')
MemberCheckIn.create( member_id: '7', event_id: '1', check_in_date: '2020-03-05 10:17')
MemberCheckIn.create( member_id: '9', event_id: '3', check_in_date: '2020-04-07 08:13')
MemberCheckIn.create( member_id: '1', event_id: '1', check_in_date: '2020-03-24 02:19')
MemberCheckIn.create( member_id: '3', event_id: '2', check_in_date: '2020-02-22 04:39')
MemberCheckIn.create( member_id: '4', event_id: '1', check_in_date: '2020-01-07 07:33')
MemberCheckIn.create( member_id: '5', event_id: '2', check_in_date: '2020-01-07 05:22')
MemberCheckIn.create( member_id: '19', event_id: '3', check_in_date: '2020-03-10 08:15')
MemberCheckIn.create( member_id: '12', event_id: '3', check_in_date: '2020-02-20 11:38')
MemberCheckIn.create( member_id: '11', event_id: '2', check_in_date: '2020-01-04 10:45')
MemberCheckIn.create( member_id: '15', event_id: '1', check_in_date: '2020-02-27 06:11')
MemberCheckIn.create( member_id: '13', event_id: '3', check_in_date: '2020-01-15 11:30')
MemberCheckIn.create( member_id: '18', event_id: '3', check_in_date: '2020-01-22 01:13')
MemberCheckIn.create( member_id: '6', event_id: '2', check_in_date: '2020-03-05 02:16')
MemberCheckIn.create( member_id: '8', event_id: '2', check_in_date: '2020-02-11 12:01')
MemberCheckIn.create( member_id: '10', event_id: '1', check_in_date: '2020-02-12 03:22')
MemberCheckIn.create( member_id: '14', event_id: '1', check_in_date: '2020-03-13 04:08')
MemberCheckIn.create( member_id: '16', event_id: '1', check_in_date: '2020-03-19 03:12')
MemberCheckIn.create( member_id: '17', event_id: '2', check_in_date: '2020-02-23 10:36')
MemberCheckIn.create( member_id: '20', event_id: '3', check_in_date: '2020-02-28 09:11')
#Officer_Status Table
OfficerStatus.create(status: '1', description: "Active")
OfficerStatus.create(status: '2', description: "Inactive")
OfficerStatus.create(status: '3', description: "Retired")
#Officer Table
Officer.create(peoplesoft_id: '1202934', officer_position_id: '2', first_name: 'Alex', middle_initial: 'A', last_name: 'Peters', date_of_birth: '1990-02-22',  address: '123 valley', city: 'Houston', zip: '23422', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '83245629348', officer_status_id: '1', payment: 'true', student_class_id: '1', major: 'CIS')
Officer.create(peoplesoft_id: '9855517', officer_position_id: '3', first_name: 'Joey', middle_initial: 'B', last_name: 'Waters', date_of_birth: '1992-11-10',  address: '233 Tempus', city: 'Houston', zip: '86553', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '8324765843', officer_status_id: '2', payment: 'true', student_class_id: '2', major: 'CIS')
Officer.create(peoplesoft_id: '8682163', officer_position_id: '2', first_name: 'Fernando', middle_initial: 'C', last_name: 'Hilman', date_of_birth: '1989-07-04',  address: '222 Rodeo lane', city: 'Houston', zip: '34657', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '7136948374', officer_status_id: '1', payment: 'true', student_class_id: '1', major: 'CIS')
Officer.create(peoplesoft_id: '3646184', officer_position_id: '1', first_name: 'Alexis', middle_initial: 'D', last_name: 'Wringley', date_of_birth: '1991-05-10',  address: '3923 Knight road', city: 'Kingwood', zip: '89796', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '8326789405', officer_status_id: '1', payment: 'true', student_class_id: '2', major: 'CIS')
Officer.create(peoplesoft_id: '9483899', officer_position_id: '3', first_name: 'Terry', middle_initial: 'W', last_name: 'Martinez', date_of_birth: '1992-03-25',  address: '999 General street', city: 'Houston', zip: '78969', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '7135867363', officer_status_id: '1', payment: 'true', student_class_id: '1', major: 'CIS')
Officer.create(peoplesoft_id: '1251353', officer_position_id: '1', first_name: 'Virginia', middle_initial: 'G', last_name: 'Detillier', date_of_birth: '1992-04-25',  address: '89 Central road', city: 'Houston', zip: '77055', state_id: '10', country_id: '1', home_phone: '2813646079', mobile_phone: '2810983746', officer_status_id: '2', payment: 'true', student_class_id: '1', major: 'MIS')
Officer.create(peoplesoft_id: '3574182', officer_position_id: '3', first_name: 'Ashley', middle_initial: 'D', last_name: 'Kinsey', date_of_birth: '1990-10-15',  address: '573 Fallen Oak ', city: 'Houston', zip: '77039', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '2813645295', officer_status_id: '2', payment: 'true', student_class_id: '2', major: 'CIS')
Officer.create(peoplesoft_id: '1906667', officer_position_id: '2', first_name: 'John', middle_initial: 'H', last_name: 'Osweiller', date_of_birth: '1989-11-07',  address: '23 Danish', city: 'Tomball', zip: '73543', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '7139475628', officer_status_id: '2', payment: 'true', student_class_id: '1', major: 'CIS')
Officer.create(peoplesoft_id: '9433638', officer_position_id: '4', first_name: 'Ross', middle_initial: 'K', last_name: 'Krebs', date_of_birth: '2000-02-01',  address: '66 Water Park', city: 'Houston', zip: '72645', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '8324785624', officer_status_id: '2', payment: 'true', student_class_id: '2', major: 'CIS')
Officer.create(peoplesoft_id: '4867722', officer_position_id: '1', first_name: 'Sasha', middle_initial: 'U', last_name: 'Hernandez', date_of_birth: '1992-10-13',  address: '3922 Park row', city: 'Houston', zip: '72344', state_id: '10', country_id: '1', home_phone: '2814863724', mobile_phone: '71396837583', officer_status_id: '1', payment: 'true', student_class_id: '1', major: 'CIS')
Officer.create(peoplesoft_id: '8011975', officer_position_id: '2', first_name: 'Cody', middle_initial: 'P', last_name: 'Smith', date_of_birth: '1993-05-14',  address: '345 Broken road', city: 'Houston', zip: '7893', state_id: '10', country_id: '1', home_phone: '7137572847345', mobile_phone: '2813746562', officer_status_id: '2', payment: 'true', student_class_id: '2', major: 'CIS')
Officer.create(peoplesoft_id: '8242361', officer_position_id: '3', first_name: 'Joshua', middle_initial: 'F', last_name: 'Wood', date_of_birth: '1994-06-18',  address: '23 Sunlight street', city: 'Houston', zip: '794563', state_id: '10', country_id: '1', home_phone: '2817564039509', mobile_phone: '8324756364', officer_status_id: '1', payment: 'true', student_class_id: '2', major: 'MIS')
Officer.create(peoplesoft_id: '6896543', officer_position_id: '2', first_name: 'Jose', middle_initial: 'K', last_name: 'Tilman', date_of_birth: '1995-10-04',  address: '539 Woodlands', city: 'Houston', zip: '79453', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '832460953958', officer_status_id: '2', payment: 'true', student_class_id: '2', major: 'CIS')
Officer.create(peoplesoft_id: '9252682', officer_position_id: '4', first_name: 'Jesus', middle_initial: 'L', last_name: 'Mendoza', date_of_birth: '1990-05-30',  address: '2394 Highway', city: 'Houston', zip: '78452', state_id: '10', country_id: '1', home_phone: '28140596874', mobile_phone: '83240596857', officer_status_id: '1', payment: 'true', student_class_id: '1', major: 'CIS')
Officer.create(peoplesoft_id: '4605428', officer_position_id: '3', first_name: 'Shaila', middle_initial: 'Q', last_name: 'Walters', date_of_birth: '1991-11-24',  address: '548 Morning Lane', city: 'Spring', zip: '77043', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '7130495867', officer_status_id: '2', payment: 'true', student_class_id: '1', major: 'CIS')
Officer.create(peoplesoft_id: '5484536', officer_position_id: '3', first_name: 'Maritza', middle_initial: 'E', last_name: 'Lane', date_of_birth: '1989-12-21',  address: '3420 Shaggy road', city: 'Houston', zip: '78333', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '8324019562', officer_status_id: '2', payment: 'true', student_class_id: '1', major: 'CIS')
Officer.create(peoplesoft_id: '8033900', officer_position_id: '2', first_name: 'Karen', middle_initial: 'O', last_name: 'Nguyen', date_of_birth: '1994-02-22',  address: '2234 Guitar lane', city: 'Katy', zip: 74532', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '7132472873', officer_status_id: '1', payment: 'true', student_class_id: '2', major: 'CIS')
Officer.create(peoplesoft_id: '2812954', officer_position_id: '4', first_name: 'Lorenzo', middle_initial: 'M', last_name: 'Song', date_of_birth: '1995-08-10',  address: '293 Pacific road', city: 'Houston', zip: '77843', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '7134856385', officer_status_id: '2', payment: 'true', student_class_id: '1', major: 'CIS')
Officer.create(peoplesoft_id: '7925924', officer_position_id: '1', first_name: 'Freddy', middle_initial: 'W', last_name: 'Clark', date_of_birth: '1996-04-11',  address: '2348 Ocean street', city: 'Sugarland', zip: '77343', state_id: '10', country_id: '1', home_phone: '2810394857', mobile_phone: '83249586746', officer_status_id: '1', payment: 'true', student_class_id: '2', major: 'MIS')
Officer.create(peoplesoft_id: '5792868', officer_position_id: '1', first_name: 'Lori', middle_initial: 'D', last_name: 'Fields', date_of_birth: '1997-06-26',  address: '230 Candle road', city: 'Houston', zip: '77431', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '2814758673', officer_status_id: '2', payment: 'true', student_class_id: '1', major: 'CIS')
#Officer_Check_In Table
OfficerCheckIn.create(officer_id: '1', event_id: '4', check_in_date: '2020-01-10')
OfficerCheckIn.create(officer_id: '2', event_id: '2', check_in_date: '2020-02-11')
OfficerCheckIn.create(officer_id: '2', event_id: '4', check_in_date: '2020-03-01')
OfficerCheckIn.create(officer_id: '1', event_id: '5', check_in_date: '2020-01-22')
OfficerCheckIn.create(officer_id: '3', event_id: '1', check_in_date: '2020-01-30')
OfficerCheckIn.create(officer_id: '1', event_id: '2', check_in_date: '2020-02-15')
OfficerCheckIn.create(officer_id: '1', event_id: '1', check_in_date: '2020-02-14')
OfficerCheckIn.create(officer_id: '2', event_id: '2', check_in_date: '2020-03-15')
OfficerCheckIn.create(officer_id: '3', event_id: '3', check_in_date: '2020-01-19')
OfficerCheckIn.create(officer_id: '1', event_id: '3', check_in_date: '2020-02-22')
OfficerCheckIn.create(officer_id: '3', event_id: '1', check_in_date: '2020-02-29')
OfficerCheckIn.create(officer_id: '3', event_id: '3', check_in_date: '2020-01-30')
OfficerCheckIn.create(officer_id: '1', event_id: '2', check_in_date: '2020-03-25')
OfficerCheckIn.create(officer_id: '3', event_id: '1', check_in_date: '2020-03-31')
OfficerCheckIn.create(officer_id: '2', event_id: '4', check_in_date: '2020-02-20')
OfficerCheckIn.create(officer_id: '1', event_id: '3', check_in_date: '2020-02-28')
OfficerCheckIn.create(officer_id: '2', event_id: '2', check_in_date: '2020-01-11')
OfficerCheckIn.create(officer_id: '2', event_id: '4', check_in_date: '2020-01-15')
OfficerCheckIn.create(officer_id: '1', event_id: '4', check_in_date: '2020-02-28')
OfficerCheckIn.create(officer_id: '1', event_id: '1', check_in_date: '2020-03-14')
#Coordinator_Status Table
CoordinatorStatus.create(status: '1', description: "Active")
CoordinatorStatus.create(status: '2', description: "Inactive")
CoordinatorStatus.create(status: '3', description: "Retired")
#Coordinator_Position Table
CoordinatorPosition.create(position: 'Social Media', description: 'In charge of platform contents')
CoordinatorPosition.create(position: 'Outreach', description: 'In charge of reaching new students')
CoordinatorPosition.create(position: 'Designer', description: 'In charge of the look of association')
#Coordinator Table
Coordinator.create(peoplesoft_id: '2922118', coordinator_position_id: '1', first_name: 'Liliana', middle_initial: 'A', last_name: 'Mason', date_of_birth: '1990-10-04', address: '234 Confession Lane', city: 'Houston', zip: '77834', state_id: '10', country_id: '1', home_phone: '7130848261', mobile_phone: '8329462736', coordinator_status_id: '1', payment: 'true', student_class_id: '1', major: 'CIS')
Coordinator.create(peoplesoft_id: '1543631', coordinator_position_id: '3', first_name: 'Eduardo', middle_initial: 'E', last_name: 'Brown', date_of_birth: '1992-04-12', address: '22823 Ladybug street', city: 'Houston', zip: '79333', state_id: '10', country_id: '1', home_phone: '7130693751', mobile_phone: '8323957382', coordinator_status_id: '1', payment: 'true', student_class_id: '2', major: 'CIS')
Coordinator.create(peoplesoft_id: '1988579', coordinator_position_id: '2', first_name: 'Nayeli', middle_initial: 'C', last_name: 'Osorio', date_of_birth: '1989-02-10', address: '987 River lane', city: 'Katy', zip: '78594', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '7132047383', coordinator_status_id: '1', payment: 'true', student_class_id: '1', major: 'CIS')
Coordinator.create(peoplesoft_id: '8449458', coordinator_position_id: '1', first_name: 'Morgan', middle_initial: '', last_name: 'Livingston', date_of_birth: '1988-07-03', address: '356 String lane', city: 'Houston', zip: '77233', state_id: '10', country_id: '1', home_phone: '2810485764', mobile_phone: '2812946284', coordinator_status_id: '1', payment: 'true', student_class_id: '2', major: 'CIS')
Coordinator.create(peoplesoft_id: '2346075', coordinator_position_id: '2', first_name: 'Ezequiel', middle_initial: 'E', last_name: 'Grass', date_of_birth: '1993-05-13', address: '542 Smiley trail', city: 'Houston', zip: '77235', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '7130294727', coordinator_status_id: '1', payment: 'true', student_class_id: '1', major: 'CIS')
Coordinator.create(peoplesoft_id: '5442856', coordinator_position_id: '2', first_name: 'Raul', middle_initial: 'C', last_name: 'Flores', date_of_birth: '1991-12-24', address: '232 Casper lane', city: 'Woodlands', zip: '77383', state_id: '10', country_id: '1', home_phone: '7134959684', mobile_phone: '2812940284', coordinator_status_id: '2', payment: 'false', student_class_id: '2', major: 'CIS')
Coordinator.create(peoplesoft_id: '1595979', coordinator_position_id: '1', first_name: 'Erika', middle_initial: 'W', last_name: 'Mavris', date_of_birth: '1990-11-11', address: '1234 Mist road', city: 'Houston', zip: '79323', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '7130294782', coordinator_status_id: '1', payment: 'true', student_class_id: '2', major: 'CIS')
Coordinator.create(peoplesoft_id: '4585473', coordinator_position_id: '3', first_name: 'Shawn', middle_initial: '', last_name: 'Lewis', date_of_birth: '1988-02-11', address: '237 Winners court', city: 'Pearland', zip: '77283', state_id: '10', country_id: '1', home_phone: '2812046485', mobile_phone: '8324058375', coordinator_status_id: '1', payment: 'true', student_class_id: '1', major: 'CIS')
Coordinator.create(peoplesoft_id: '7582254', coordinator_position_id: '2', first_name: 'Julia', middle_initial: '', last_name: 'Bew', date_of_birth: '1991-04-10', address: '2348 Education lane', city: 'Houston', zip: '77346', state_id: '10', country_id: '1', home_phone: '', mobile_phone: '2810294736', coordinator_status_id: '1', payment: 'true', student_class_id: 1'', major: 'CIS')
Coordinator.create(peoplesoft_id: '7582254', coordinator_position_id: '1', first_name: 'Jerry', middle_initial: 'R', last_name: 'Nao', date_of_birth: '1993-06-23', address: '8237 Skinner road', city: 'Houston', zip: '79892', state_id: '10', country_id: '1', home_phone: '2810093947', mobile_phone: '7132294857', coordinator_status_id: '1', payment: 'true', student_class_id: '2', major: 'CIS')
#Coordinator_Check_In Table
CoordinatorCheckIn.create(coordinator_id: '8', event_id: '2', check_in_date: '2020-01-13')
CoordinatorCheckIn.create(coordinator_id: '1', event_id: '5', check_in_date: '2020-04-01')
CoordinatorCheckIn.create(coordinator_id: '3', event_id: '7', check_in_date: '2020-04-07')
CoordinatorCheckIn.create(coordinator_id: '4', event_id: '2', check_in_date: '2020-03-15')
CoordinatorCheckIn.create(coordinator_id: '6', event_id: '8', check_in_date: '2020-02-28')
CoordinatorCheckIn.create(coordinator_id: '2', event_id: '10', check_in_date: '2020-01-21')
CoordinatorCheckIn.create(coordinator_id: '7', event_id: '12', check_in_date: '2020-01-30')
CoordinatorCheckIn.create(coordinator_id: '2', event_id: '06', check_in_date: '2020-02-01')
CoordinatorCheckIn.create(coordinator_id: '4', event_id: '05', check_in_date: '2020-01-12')
CoordinatorCheckIn.create(coordinator_id: '6', event_id: '13', check_in_date: '2020-04-01')
CoordinatorCheckIn.create(coordinator_id: '5', event_id: '02', check_in_date: '2020-03-19')
CoordinatorCheckIn.create(coordinator_id: '3', event_id: '01', check_in_date: '2020-02-21')
CoordinatorCheckIn.create(coordinator_id: '1', event_id: '09', check_in_date: '2020-02-14')
CoordinatorCheckIn.create(coordinator_id: '3', event_id: '12', check_in_date: '2020-01-10')
CoordinatorCheckIn.create(coordinator_id: '5', event_id: '11', check_in_date: '2020-01-03')
CoordinatorCheckIn.create(coordinator_id: '7', event_id: '13', check_in_date: '2020-02-27')
CoordinatorCheckIn.create(coordinator_id: '3', event_id: '15', check_in_date: '2020-03-20')
CoordinatorCheckIn.create(coordinator_id: '2', event_id: '02', check_in_date: '2020-03-28')
CoordinatorCheckIn.create(coordinator_id: '1', event_id: '04', check_in_date: '2020-02-13')
CoordinatorCheckIn.create(coordinator_id: '2', event_id: '05', check_in_date: '2020-01-15')
