# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: '2')
#Country Table
Country.create_or_find_by(name: "United States", country_abbreviation: "USA")
Country.create_or_find_by(name: "Canada", country_abbreviation: "CAN")
#State Table
State.create_or_find_by(country_id: '1', name: "Texas", state_abbreviation: "TX")
State.create_or_find_by(country_id: '1', name: "Alabama", state_abbreviation: "AL")
State.create_or_find_by(country_id: '1', name: "Alaska", state_abbreviation: "AK")
State.create_or_find_by(country_id: '2', name: "Alberta", state_abbreviation: "AB")
State.create_or_find_by(country_id: '1', name: "Arizona", state_abbreviation: "AZ")
State.create_or_find_by(country_id: '1', name: "Arkansas", state_abbreviation: "AR")
State.create_or_find_by(country_id: '2', name: "British Columbia", state_abbreviation: "BC")
State.create_or_find_by(country_id: '1', name: "California", state_abbreviation: "CA")
State.create_or_find_by(country_id: '1', name: "Colorado", state_abbreviation: "CO")
State.create_or_find_by(country_id: '1', name: "Connecticut", state_abbreviation: "CT")
State.create_or_find_by(country_id: '1', name: "Delaware", state_abbreviation: "DE")
State.create_or_find_by(country_id: '1', name: "Florida", state_abbreviation: "FL")
State.create_or_find_by(country_id: '1', name: "Georgia", state_abbreviation: "GA")
State.create_or_find_by(country_id: '1', name: "Hawaii", state_abbreviation: "HI")
State.create_or_find_by(country_id: '1', name: "Idaho", state_abbreviation: "ID")
State.create_or_find_by(country_id: '1', name: "Illinois", state_abbreviation: "IL")
State.create_or_find_by(country_id: '1', name: "Indiana", state_abbreviation: "IN")
State.create_or_find_by(country_id: '1', name: "Iowa", state_abbreviation: "IA")
State.create_or_find_by(country_id: '1', name: "Kansas", state_abbreviation: "KS")
State.create_or_find_by(country_id: '1', name: "Kentucky", state_abbreviation: "KY")
State.create_or_find_by(country_id: '2', name: "Labrador", state_abbreviation: "LB")
State.create_or_find_by(country_id: '1', name: "Louisiana", state_abbreviation: "LA")
State.create_or_find_by(country_id: '1', name: "Maine", state_abbreviation: "ME")
State.create_or_find_by(country_id: '2', name: "Manitoba", state_abbreviation: "MB")
State.create_or_find_by(country_id: '1', name: "Maryland", state_abbreviation: "MD")
State.create_or_find_by(country_id: '1', name: "Massachusetts", state_abbreviation: "MA")
State.create_or_find_by(country_id: '1', name: "Michigan", state_abbreviation: "MI")
State.create_or_find_by(country_id: '1', name: "Minnesota", state_abbreviation: "MN")
State.create_or_find_by(country_id: '1', name: "Mississippi", state_abbreviation: "MS")
State.create_or_find_by(country_id: '1', name: "Missouri", state_abbreviation: "MO")
State.create_or_find_by(country_id: '1', name: "Montana", state_abbreviation: "MT")
State.create_or_find_by(country_id: '1', name: "Nebraska", state_abbreviation: "NE")
State.create_or_find_by(country_id: '1', name: "Nevada", state_abbreviation: "NV")
State.create_or_find_by(country_id: '2', name: "New Brunswick", state_abbreviation: "NB")
State.create_or_find_by(country_id: '1', name: "New Hampshire", state_abbreviation: "NH")
State.create_or_find_by(country_id: '1', name: "New Jersey", state_abbreviation: "NJ")
State.create_or_find_by(country_id: '1', name: "New Mexico", state_abbreviation: "NM")
State.create_or_find_by(country_id: '1', name: "New York", state_abbreviation: "NY")
State.create_or_find_by(country_id: '1', name: "North Carolina", state_abbreviation: "NC")
State.create_or_find_by(country_id: '1', name: "North Dakota", state_abbreviation: "ND")
State.create_or_find_by(country_id: '2', name: "Nova Scotia", state_abbreviation: "NS")
State.create_or_find_by(country_id: '2', name: "Nunavut", state_abbreviation: "NU")
State.create_or_find_by(country_id: '2', name: "North West Territory", state_abbreviation: "NW")
State.create_or_find_by(country_id: '1', name: "Ohio", state_abbreviation: "OH")
State.create_or_find_by(country_id: '1', name: "Oklahoma", state_abbreviation: "OK")
State.create_or_find_by(country_id: '2', name: "Ontario", state_abbreviation: "ON")
State.create_or_find_by(country_id: '1', name: "Oregon", state_abbreviation: "OR")
State.create_or_find_by(country_id: '1', name: "Pennsylvania", state_abbreviation: "PA")
State.create_or_find_by(country_id: '2', name: "Prince Edward Island", state_abbreviation: "PE")
State.create_or_find_by(country_id: '2', name: "Quebec", state_abbreviation: "QC")
State.create_or_find_by(country_id: '1', name: "Rhode Island", state_abbreviation: "RI")
State.create_or_find_by(country_id: '2', name: "Saskatchewan", state_abbreviation: "SK")
State.create_or_find_by(country_id: '1', name: "South Carolina", state_abbreviation: "SC")
State.create_or_find_by(country_id: '1', name: "South Dakota", state_abbreviation: "SD")
State.create_or_find_by(country_id: '1', name: "Tennessee", state_abbreviation: "TN")
State.create_or_find_by(country_id: '1', name: "Texas", state_abbreviation: "TX")
State.create_or_find_by(country_id: '1', name: "Utah", state_abbreviation: "UT")
State.create_or_find_by(country_id: '1', name: "Vermont", state_abbreviation: "VT")
State.create_or_find_by(country_id: '1', name: "Virginia", state_abbreviation: "VA")
State.create_or_find_by(country_id: '1', name: "Washington", state_abbreviation: "WA")
State.create_or_find_by(country_id: '1', name: "West Virginia", state_abbreviation: "WV")
State.create_or_find_by(country_id: '1', name: "Wisconsin", state_abbreviation: "WI")
State.create_or_find_by(country_id: '1', name: "Wyoming", state_abbreviation: "WY")
State.create_or_find_by(country_id: '2', name: "Yukon", state_abbreviation: "YT")
#Student_Class Table
StudentClass.create_or_find_by(student_class: "Freshman", description: "A First Year Student")
StudentClass.create_or_find_by(student_class: "Sophomore", description: "A Second Year Student")
StudentClass.create_or_find_by(student_class: "Junior", description: "A Third Year Student")
StudentClass.create_or_find_by(student_class: "Senior", description: "A Fourth Year Student")
#Member_Status Table
MemberStatus.create_or_find_by(status: "Active", description: "This is an active member")
MemberStatus.create_or_find_by(status: "Inactive", description: "This is an inactive member")
#Member Table
Member.create_or_find_by(peoplesoft_id: "1402934", first_name: "Josh", middle_initial: "A", last_name: "Smith", date_of_birth: "1998-02-22",  address: "4323 Quaker Oats", city: "Houston", zip: "77004", state_id: '1', country_id: '1', home_phone: "281-938-4232", mobile_phone: "832-456-2938", member_status_id: '1', payment: 'true', student_class_id: '3', major: "CIS")
Member.create_or_find_by(peoplesoft_id: "1435690", first_name: "April", middle_initial: "W", last_name: "Green", date_of_birth: "1997-12-05",  address: "3284 Bingo Dr", city: "Sugar Land", zip: "77479", state_id: '1', country_id: '1', home_phone: "832-493-5429", mobile_phone: "281-438-9422", member_status_id: '1', payment: 'true', student_class_id: '4', major: "CIS")
Member.create_or_find_by(peoplesoft_id: "1484952", first_name: "Frank", middle_initial: "V", last_name: "House", date_of_birth: "1999-01-08",  address: "853 Andrew Jackson Street", city: "Houston", zip: "77004", state_id: '1', country_id: '1', home_phone: "", mobile_phone: "832-539-5923", member_status_id: '2', payment: 'false', student_class_id: '2', major: "CIS")
Member.create_or_find_by(peoplesoft_id: "1438295", first_name: "Cory", middle_initial: "", last_name: "Jackson", date_of_birth: "1998-07-13",  address: "2432 Harden Garden", city: "Stafford", zip: "77497", state_id: '1', country_id: '1', home_phone: "281-639-2748", mobile_phone: "713-539-5923", member_status_id: '1', payment: 'true', student_class_id: '3', major: "MIS")
Member.create_or_find_by(peoplesoft_id: "1459038", first_name: "Blake", middle_initial: "M", last_name: "Robinson", date_of_birth: "1996-09-26",  address: "438 Rose Drive", city: "Houston", zip: "77004", state_id: '1', country_id: '1', home_phone: "281-394-5902", mobile_phone: "832-346-3438", member_status_id: '2', payment: 'false', student_class_id: '4', major: "CIS")
Member.create_or_find_by(peoplesoft_id: "1443820", first_name: "Jim", middle_initial: "E", last_name: "Brown", date_of_birth: "1999-12-05",  address: "3284 Bingo Dr", city: "Katy", zip: "77494", state_id: '1', country_id: '1', home_phone: "832-538-9382", mobile_phone: "281-443-3289", member_status_id: '1', payment: 'true', student_class_id: '1', major: "CIS")
Member.create_or_find_by(peoplesoft_id: "1468495", first_name: "Michael", middle_initial: "J", last_name: "Davidson", date_of_birth: "1998-11-28",  address: "632 Roscoe Park", city: "Houston", zip: "77004", state_id: '1', country_id: '1', home_phone: "832-443-5649", mobile_phone: "281-329-5443", member_status_id: '1', payment: 'true', student_class_id: '2', major: "CIS")
Member.create_or_find_by(peoplesoft_id: "1443830", first_name: "Howard", middle_initial: "", last_name: "Josh", date_of_birth: "2000-01-01",  address: "632 Roscoe Park", city: "Richmond", zip: "77469", state_id: '1', country_id: '1', home_phone: "281-323-5532", mobile_phone: "713-432-9328", member_status_id: '1', payment: 'true', student_class_id: '1', major: "MIS")
Member.create_or_find_by(peoplesoft_id: "1464283", first_name: "Rob", middle_initial: "P", last_name: "White", date_of_birth: "1996-04-07",  address: "9542 Hershey Road", city: "Houston", zip: "77004", state_id: '1', country_id: '1', home_phone: "", mobile_phone: "832-346-3438", member_status_id: '2', payment: 'false', student_class_id: '4', major: "CIS")
Member.create_or_find_by(peoplesoft_id: "1493284", first_name: "Megan", middle_initial: "", last_name: "Pearson", date_of_birth: "1997-10-23",  address: "5320 Forest Trail ", city: "Houston", zip: "77004", state_id: '1', country_id: '1', home_phone: "713-943-5392", mobile_phone: "832-932-4382", member_status_id: '2', payment: 'false', student_class_id: '4', major: "CIS")
#Sponsor_type Table
SponsorType.create_or_find_by(sponsor_type: "Oil and Gas", description: "Companies that are in the oil and gas field")
SponsorType.create_or_find_by(sponsor_type: "Consulting", description: "Companies that are in the consulting field")
SponsorType.create_or_find_by(sponsor_type: "Electricity", description: "Companies that are in the electricity field")
SponsorType.create_or_find_by(sponsor_type: "Technology", description: "Companies that are in the technology field")
#Sponsor Table
Sponsor.create_or_find_by(company: "Shell", first_name: "Josh", last_name: "Smith", home_phone: "281-839-2333", mobile_phone: "832-881-4824", sponsor_type_id: '1')
Sponsor.create_or_find_by(company: "Exxon", first_name: "Robert", last_name: "Costales", home_phone: "331-924-2341", mobile_phone: "434-423-9432", sponsor_type_id: '1')
Sponsor.create_or_find_by(company: "Reynolds & Reynolds", first_name: "Layla", last_name: "Reese", home_phone: "281-553-5325", mobile_phone: "832-831-4714", sponsor_type_id: '2')
Sponsor.create_or_find_by(company: "HP", first_name: "Shang", last_name: "Wei", home_phone: "281-112-4532", mobile_phone: "832-131-4842", sponsor_type_id: '4')
Sponsor.create_or_find_by(company: "Chevron", first_name: "Becky", last_name: "Black", home_phone: "281-199-2293", mobile_phone: "832-402-0049", sponsor_type_id: '1')
Sponsor.create_or_find_by(company: "Reliant Energy", first_name: "Steve", last_name: "Ortega", home_phone: "281-491-3920", mobile_phone: "832-111-4804", sponsor_type_id: '3')
Sponsor.create_or_find_by(company: "Microsoft", first_name: "Angela", last_name: "Fling", home_phone: "221-209-4523", mobile_phone: "832-609-4815", sponsor_type_id: '4')
Sponsor.create_or_find_by(company: "TXU Energy", first_name: "Richard", last_name: "Dold", home_phone: "281-800-2573", mobile_phone: "832-612-1514", sponsor_type_id: '3')
Sponsor.create_or_find_by(company: "Accenture", first_name: "John", last_name: "Medina", home_phone: "281-989-2113", mobile_phone: "832-617-4592", sponsor_type_id: '2')
Sponsor.create_or_find_by(company: "Bain & Company", first_name: "Anthony", last_name: "Mekhail", home_phone: "281-129-2050", mobile_phone: "832-831-8230", sponsor_type_id: '2')
Sponsor.create_or_find_by(company: "Apple", first_name: "Andrew", last_name: "Ewing", home_phone: "281-109-2000", mobile_phone: "832-901-9034", sponsor_type_id: '4')
Sponsor.create_or_find_by(company: "IBM", first_name: "Katie", last_name: "Clark", home_phone: "281-819-2940", mobile_phone: "832-431-9280", sponsor_type_id: '4')
Sponsor.create_or_find_by(company: "Texaco", first_name: "Alyssa", last_name: "Jade", home_phone: "281-194-2850", mobile_phone: "832-849-4829", sponsor_type_id: '1')
Sponsor.create_or_find_by(company: "Samsung", first_name: "Colton", last_name: "Larp", home_phone: "281-029-9033", mobile_phone: "832-801-4928", sponsor_type_id: '4')
Sponsor.create_or_find_by(company: "Facebook", first_name: "Elaine", last_name: "Ta", home_phone: "281-490-2003", mobile_phone: "832-191-4284", sponsor_type_id: '4')
Sponsor.create_or_find_by(company: "Boston Consulting Group", first_name: "Ronald", last_name: "Oviedo", home_phone: "281-809-4333", mobile_phone: "832-381-1844", sponsor_type_id: '2')
Sponsor.create_or_find_by(company: "Deloitte", first_name: "Braden", last_name: "Kosher", home_phone: "281-839-2423", mobile_phone: "832-981-4390", sponsor_type_id: '2')
Sponsor.create_or_find_by(company: "Lukoil", first_name: "Alexander", last_name: "Mond", home_phone: "281-919-2303", mobile_phone: "832-850-4800", sponsor_type_id: '1')
Sponsor.create_or_find_by(company: "Total", first_name: "Sidney", last_name: "Deblanc", home_phone: "281-592-0333", mobile_phone: "832-681-4584", sponsor_type_id: '1')
Sponsor.create_or_find_by(company: "Intel", first_name: "Blake", last_name: "Griffin", home_phone: "281-849-0385", mobile_phone: "832-884-8103", sponsor_type_id: '4')
Sponsor.create_or_find_by(company: "KPMG", first_name: "Cody", last_name: "Vong", home_phone: "281-801-0433", mobile_phone: "832-190-4904", sponsor_type_id: '2')
Sponsor.create_or_find_by(company: "Mercer", first_name: "Morgan", last_name: "Prak", home_phone: "281-894-1893", mobile_phone: "832-194-0591", sponsor_type_id: '2')
Sponsor.create_or_find_by(company: "Spark Energy", first_name: "Veronica", last_name: "Lamone", home_phone: "281-809-2033", mobile_phone: "832-094-4514", sponsor_type_id: '3')
Sponsor.create_or_find_by(company: "Solarplicity", first_name: "Brandon", last_name: "Tep", home_phone: "281-1943", mobile_phone: "832-081-4856", sponsor_type_id: '3')
Sponsor.create_or_find_by(company: "Cirro Energy", first_name: "Travis", last_name: "Tran", home_phone: "281-019-9533", mobile_phone: "832-941-4004", sponsor_type_id: '3')
#Event_Status Table
EventStatus.create_or_find_by(status: "In Progress", description: "Event is in progress")
EventStatus.create_or_find_by(status: "Planned", description: "Event is planned")
EventStatus.create_or_find_by(status: "Cancelled", description: "Event was cancelled")
EventStatus.create_or_find_by(status: "Completed", description: "Event was completed")
#Event_Type Table
EventType.create_or_find_by(event_type: "Fundraiser", description: "Helps raise money for Association")
EventType.create_or_find_by(event_type: "Meeting", description: "Brings professionals to University to talk to students")
EventType.create_or_find_by(event_type: "Tutoring", description: "Help students with class homework")
EventType.create_or_find_by(event_type: "Open Discussion", description: "To discuss events such as voting for new board members")
EventType.create_or_find_by(event_type: "Competition", description: "Competition for students")
EventType.create_or_find_by(event_type: "Workshop", description: "Workshops to help students")
EventType.create_or_find_by(event_type: "Help Session", description: "Career and school related help for students")
#Event Table
Event.create_or_find_by(description: "Week 1: AITP General Meeting", event_date: '2019-08-29', event_type_id: '2', event_status_id: '4', sponsor_id: '4', fee: '0.00', address: "156 Golf View Pass", building_name: "T1", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 2: AITP Career Help Session Week", event_date: '2019-09-05', event_type_id: '7', event_status_id: '4', sponsor_id: '5', fee: '0.00', address: "3476 Dorton Crossing", building_name: "T2", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 3: AITP Resume Workshop", event_date: '2019-09-20', event_type_id: '6', event_status_id: '4', sponsor_id: '11', fee: '0.00', address: "156 Golf View Pass", building_name: "T2", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 4: AITP Officers Meeting", event_date: '2019-09-30', event_type_id: '2', event_status_id: '4', sponsor_id: '13', fee: '0.00', address: "5510 Sunny Valley Ln", building_name: "A2", city: "Houston", zip: "77048", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 5: AITP General Meeting", event_date: '2019-10-10', event_type_id: '2', event_status_id: '4', sponsor_id: '16', fee: '0.00', address: "555 University Lane", building_name: "B2", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 6: AITP Cat's Back Booth", event_date: '2020-04-02', event_type_id: '4', event_status_id: '1', sponsor_id: '8', fee: '0.00', address: "555 University Lane", building_name: "B2", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 7: AITP Tutoring Session", event_date: '2020-04-09', event_type_id: '3', event_status_id: '4', sponsor_id: '20', fee: '0.00', address: "555 University Lane", building_name: "B2", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 8: AITP General Meeting", event_date: '2020-05-01', event_type_id: '2', event_status_id: '4', sponsor_id: '25', fee: '0.00', address: "555 University Lane", building_name: "B2", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 9: AITP Fundraising Event", event_date: '2020-04-15', event_type_id: '1', event_status_id: '2', sponsor_id: '14', fee: '0.00', address: "134 Technology Rd", building_name: "X2", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 10: AITP Officers Meeting", event_date: '2020-02-14', event_type_id: '2', event_status_id: '4', sponsor_id: '1', fee: '0.00', address: "555 University Lane", building_name: "C2", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 11: AITP General Meeting", event_date: '2020-02-21', event_type_id: '2', event_status_id: '4', sponsor_id: '3', fee: '0.00', address: "555 University Lane", building_name: "B2", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 12: AITP Resume Workshop", event_date: '2020-02-07', event_type_id: '6', event_status_id: '3', sponsor_id: '2', fee: '0.00', address: "555 University Lane", building_name: "B2", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 13: AITP Competition", event_date: '2020-02-28', event_type_id: '5', event_status_id: '4', sponsor_id: '9', fee: '0.00', address: "555 University Lane", building_name: "B2", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 14: AITP General Meeting", event_date: '2020-05-07', event_type_id: '2', event_status_id: '4', sponsor_id: '19', fee: '0.00', address: "555 University Lane", building_name: "B2", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 15: AITP General Meeting", event_date: '2020-03-28', event_type_id: '2', event_status_id: '4', sponsor_id: '22', fee: '0.00', address: "555 University Lane", building_name: "A2", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 16: AITP Coordinators Meeting", event_date: '2020-03-20', event_type_id: '2', event_status_id: '3', sponsor_id: '6', fee: '0.00', address: "555 University Lane", building_name: "T1", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 17: AITP General Meeting", event_date: '2020-03-01', event_type_id: '2', event_status_id: '4', sponsor_id: '18', fee: '0.00', address: "735 Research Forest", building_name: "R2", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 18: AITP General Meeting", event_date: '2020-01-12', event_type_id: '2', event_status_id: '4', sponsor_id: '17', fee: '0.00', address: "555 University Lane", building_name: "C3", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 19: AITP Fundraising Event", event_date: '2020-04-08', event_type_id: '1', event_status_id: '2', sponsor_id: '12', fee: '0.00', address: "555 University Lane", building_name: "A4", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 20: AITP General Meeting", event_date: '2020-04-25', event_type_id: '2', event_status_id: '3', sponsor_id: '15', fee: '0.00', address: "123 Misty Road", building_name: "W2", city: "Waco", zip: "77189", state_id: '1', country_id: '1')
Event.create_or_find_by(description: "Week 21: AITP General Meeting", event_date: '2020-03-10', event_type_id: '2', event_status_id: '4', sponsor_id: '7', fee: '0.00', address: "555 University Lane", building_name: "A2", city: "Houston", zip: "77004", state_id: '1', country_id: '1')
#Member_Check_In Table
MemberCheckIn.create_or_find_by( member_id: '2', event_id: '16', check_in_date: '2020-01-07 12:31:12')
MemberCheckIn.create_or_find_by( member_id: '4', event_id: '5', check_in_date: '2020-02-20 02:03:53')
MemberCheckIn.create_or_find_by( member_id: '7', event_id: '18', check_in_date: '2020-03-05 10:17:42')
MemberCheckIn.create_or_find_by( member_id: '9', event_id: '14', check_in_date: '2020-04-07 08:13:56')
MemberCheckIn.create_or_find_by( member_id: '1', event_id: '20', check_in_date: '2020-03-24 02:19:58')
MemberCheckIn.create_or_find_by( member_id: '3', event_id: '19', check_in_date: '2020-02-22 04:39:30')
MemberCheckIn.create_or_find_by( member_id: '4', event_id: '21', check_in_date: '2020-01-07 07:33:20')
MemberCheckIn.create_or_find_by( member_id: '5', event_id: '7', check_in_date: '2020-01-07 05:22:47')
MemberCheckIn.create_or_find_by( member_id: '10', event_id: '19', check_in_date: '2020-03-10 08:15:29')
MemberCheckIn.create_or_find_by( member_id: '8', event_id: '4', check_in_date: '2020-02-20 11:38:33')
MemberCheckIn.create_or_find_by( member_id: '6', event_id: '17', check_in_date: '2020-01-04 10:45:29')
MemberCheckIn.create_or_find_by( member_id: '2', event_id: '13', check_in_date: '2020-02-27 06:11:24')
MemberCheckIn.create_or_find_by( member_id: '9', event_id: '7', check_in_date: '2020-01-15 11:30:22')
MemberCheckIn.create_or_find_by( member_id: '7', event_id: '18', check_in_date: '2020-01-22 01:13:13')
MemberCheckIn.create_or_find_by( member_id: '4', event_id: '1', check_in_date: '2020-03-05 02:16:04')
MemberCheckIn.create_or_find_by( member_id: '10', event_id: '2', check_in_date: '2020-02-11 12:01:06')
MemberCheckIn.create_or_find_by( member_id: '3', event_id: '14', check_in_date: '2020-02-12 03:22:39')
MemberCheckIn.create_or_find_by( member_id: '1', event_id: '8', check_in_date: '2020-03-13 04:08:56')
MemberCheckIn.create_or_find_by( member_id: '8', event_id: '16', check_in_date: '2020-03-19 03:12:32')
MemberCheckIn.create_or_find_by( member_id: '5', event_id: '4', check_in_date: '2020-02-23 10:36:38')
MemberCheckIn.create_or_find_by( member_id: '6', event_id: '3', check_in_date: '2020-02-28 09:11:24')
#Officer_Status Table
OfficerStatus.create_or_find_by(status: "Active", description: "This officer is active")
OfficerStatus.create_or_find_by(status: "Inactive", description: "This officer is inactive")
OfficerStatus.create_or_find_by(status: "Relieved", description: "This officer was relieved of their duties")
#Officer_Position Table
OfficerPosition.create_or_find_by(position: "President", description: "The president of AITP")
OfficerPosition.create_or_find_by(position: "Vice President", description: "The vice president of AITP")
OfficerPosition.create_or_find_by(position: "Treasurer", description: "The treasurer of AITP")
OfficerPosition.create_or_find_by(position: "Secretary", description: "The secretary of AITP")
#Officer Table
Officer.create_or_find_by(peoplesoft_id: '1402934', officer_position_id: '1', first_name: 'Alex', middle_initial: 'A', last_name: 'Peters', date_of_birth: '1998-02-22',  address: '123 Valley', city: 'Houston', zip: '73422', state_id: '1', country_id: '1', home_phone: '', mobile_phone: '832-456-2348', officer_status_id: '1', payment: 'true', student_class_id: '3', major: 'CIS')
Officer.create_or_find_by(peoplesoft_id: '1455517', officer_position_id: '2', first_name: 'Joey', middle_initial: '', last_name: 'Waters', date_of_birth: '1995-11-10',  address: '233 Tempus', city: 'Houston', zip: '76553', state_id: '1', country_id: '1', home_phone: '', mobile_phone: '832-476-5843', officer_status_id: '2', payment: 'false', student_class_id: '2', major: 'CIS')
Officer.create_or_find_by(peoplesoft_id: '1482163', officer_position_id: '4', first_name: 'Fernando', middle_initial: 'C', last_name: 'Hilman', date_of_birth: '1997-07-04',  address: '222 Rodeo Lane', city: 'Houston', zip: '74657', state_id: '1', country_id: '1', home_phone: '', mobile_phone: '713-694-8374', officer_status_id: '1', payment: 'true', student_class_id: '4', major: 'CIS')
Officer.create_or_find_by(peoplesoft_id: '1446184', officer_position_id: '3', first_name: 'Alexis', middle_initial: 'D', last_name: 'Wringley', date_of_birth: '1996-05-10',  address: '3923 Knight Road', city: 'Kingwood', zip: '79796', state_id: '1', country_id: '1', home_phone: '', mobile_phone: '832-678-9405', officer_status_id: '1', payment: 'true', student_class_id: '3', major: 'CIS')
Officer.create_or_find_by(peoplesoft_id: '1483899', officer_position_id: '2', first_name: 'Terry', middle_initial: 'W', last_name: 'Martinez', date_of_birth: '1998-03-25',  address: '999 General Street', city: 'Houston', zip: '78969', state_id: '1', country_id: '1', home_phone: '', mobile_phone: '713-586-7363', officer_status_id: '1', payment: 'true', student_class_id: '2', major: 'CIS')
Officer.create_or_find_by(peoplesoft_id: '1451353', officer_position_id: '3', first_name: 'Virginia', middle_initial: '', last_name: 'Washington', date_of_birth: '1995-04-25',  address: '89 Central Road', city: 'Houston', zip: '77055', state_id: '1', country_id: '1', home_phone: '281-364-6079', mobile_phone: '281-098-3746', officer_status_id: '2', payment: 'false', student_class_id: '3', major: 'MIS')
Officer.create_or_find_by(peoplesoft_id: '1474182', officer_position_id: '4', first_name: 'Ashley', middle_initial: 'D', last_name: 'Kinsey', date_of_birth: '1996-10-15',  address: '573 Fallen Oak ', city: 'Houston', zip: '77039', state_id: '1', country_id: '1', home_phone: '', mobile_phone: '281-364-5295', officer_status_id: '2', payment: 'false', student_class_id: '1', major: 'CIS')
Officer.create_or_find_by(peoplesoft_id: '1406667', officer_position_id: '2', first_name: 'John', middle_initial: 'H', last_name: 'Osweiller', date_of_birth: '1997-11-07',  address: '23 Danish', city: 'Tomball', zip: '73543', state_id: '1', country_id: '1', home_phone: '', mobile_phone: '713-947-5628', officer_status_id: '2', payment: 'false', student_class_id: '4', major: 'CIS')
Officer.create_or_find_by(peoplesoft_id: '1433638', officer_position_id: '1', first_name: 'Ross', middle_initial: '', last_name: 'Krebs', date_of_birth: '1999-02-01',  address: '66 Water Park', city: 'Houston', zip: '72645', state_id: '1', country_id: '1', home_phone: '', mobile_phone: '832-478-5624', officer_status_id: '2', payment: 'false', student_class_id: '4', major: 'CIS')
Officer.create_or_find_by(peoplesoft_id: '1467722', officer_position_id: '2', first_name: 'Sasha', middle_initial: 'U', last_name: 'Hernandez', date_of_birth: '1998-10-13',  address: '3922 Park Row', city: 'Houston', zip: '72344', state_id: '1', country_id: '1', home_phone: '281-486-3724', mobile_phone: '713-968-3583', officer_status_id: '1', payment: 'true', student_class_id: '3', major: 'CIS')
Officer.create_or_find_by(peoplesoft_id: '1411975', officer_position_id: '4', first_name: 'Cody', middle_initial: 'P', last_name: 'Smith', date_of_birth: '1996-05-14',  address: '345 Broken Road', city: 'Houston', zip: '7893', state_id: '1', country_id: '1', home_phone: '713-757-2845', mobile_phone: '281-374-6562', officer_status_id: '2', payment: 'false', student_class_id: '2', major: 'CIS')
Officer.create_or_find_by(peoplesoft_id: '1442361', officer_position_id: '3', first_name: 'Joshua', middle_initial: 'F', last_name: 'Wood', date_of_birth: '1998-06-18',  address: '23 Sunlight Street', city: 'Houston', zip: '794563', state_id: '1', country_id: '1', home_phone: '281-756-4039', mobile_phone: '832-475-6364', officer_status_id: '1', payment: 'true', student_class_id: '3', major: 'MIS')
Officer.create_or_find_by(peoplesoft_id: '1496543', officer_position_id: '1', first_name: 'Jose', middle_initial: 'K', last_name: 'Tilman', date_of_birth: '1997-10-04',  address: '539 Woodlands', city: 'Houston', zip: '79453', state_id: '1', country_id: '1', home_phone: '', mobile_phone: '832-460-9958', officer_status_id: '2', payment: 'false', student_class_id: '4', major: 'CIS')
Officer.create_or_find_by(peoplesoft_id: '1452682', officer_position_id: '3', first_name: 'Jesus', middle_initial: 'L', last_name: 'Mendoza', date_of_birth: '1997-05-30',  address: '2394 Highway', city: 'Houston', zip: '78452', state_id: '1', country_id: '1', home_phone: '281-405-9684', mobile_phone: '832-405-9657', officer_status_id: '1', payment: 'true', student_class_id: '3', major: 'CIS')
Officer.create_or_find_by(peoplesoft_id: '1405428', officer_position_id: '2', first_name: 'Shaila', middle_initial: 'Q', last_name: 'Walters', date_of_birth: '1996-11-24',  address: '548 Morning Lane', city: 'Spring', zip: '77043', state_id: '1', country_id: '1', home_phone: '', mobile_phone: '713-049-5867', officer_status_id: '2', payment: 'false', student_class_id: '1', major: 'CIS')
Officer.create_or_find_by(peoplesoft_id: '1484536', officer_position_id: '4', first_name: 'Maritza', middle_initial: '', last_name: 'Lane', date_of_birth: '1997-12-21',  address: '3420 Shaggy Road', city: 'Houston', zip: '78333', state_id: '1', country_id: '1', home_phone: '', mobile_phone: '832-401-9562', officer_status_id: '2', payment: 'false', student_class_id: '2', major: 'CIS')
Officer.create_or_find_by(peoplesoft_id: '1433900', officer_position_id: '2', first_name: 'Karen', middle_initial: 'O', last_name: 'Nguyen', date_of_birth: '1995-02-22',  address: '2234 Guitar Lane', city: 'Katy', zip: '74532', state_id: '1', country_id: '1', home_phone: '', mobile_phone: '713-247-2873', officer_status_id: '1', payment: 'true', student_class_id: '4', major: 'CIS')
Officer.create_or_find_by(peoplesoft_id: '1412954', officer_position_id: '1', first_name: 'Lorenzo', middle_initial: 'M', last_name: 'Song', date_of_birth: '1996-08-10',  address: '293 Pacific Road', city: 'Houston', zip: '77843', state_id: '1', country_id: '1', home_phone: '', mobile_phone: '713-485-6385', officer_status_id: '2', payment: 'false', student_class_id: '4', major: 'CIS')
Officer.create_or_find_by(peoplesoft_id: '1425924', officer_position_id: '2', first_name: 'Freddy', middle_initial: 'W', last_name: 'Clark', date_of_birth: '1998-04-11',  address: '2348 Ocean Street', city: 'Sugarland', zip: '77343', state_id: '1', country_id: '1', home_phone: '281-039-4857', mobile_phone: '832-495-8646', officer_status_id: '1', payment: 'true', student_class_id: '3', major: 'MIS')
Officer.create_or_find_by(peoplesoft_id: '1492868', officer_position_id: '3', first_name: 'Lori', middle_initial: 'D', last_name: 'Fields', date_of_birth: '1997-06-26',  address: '230 Candle Road', city: 'Houston', zip: '77431', state_id: '1', country_id: '1', home_phone: '', mobile_phone: '281-475-8673', officer_status_id: '2', payment: 'false', student_class_id: '2', major: 'CIS')
#Officer_Check_In Table
OfficerCheckIn.create_or_find_by(officer_id: '18', event_id: '5', check_in_date: '2020-01-10 17:21:46')
OfficerCheckIn.create_or_find_by(officer_id: '4', event_id: '21', check_in_date: '2020-02-11 15:23:56')
OfficerCheckIn.create_or_find_by(officer_id: '8', event_id: '8', check_in_date: '2020-03-01 16:04:32')
OfficerCheckIn.create_or_find_by(officer_id: '2', event_id: '1', check_in_date: '2020-01-22 16:43:35')
OfficerCheckIn.create_or_find_by(officer_id: '17', event_id: '16', check_in_date: '2020-01-30 17:16:46')
OfficerCheckIn.create_or_find_by(officer_id: '1', event_id: '11', check_in_date: '2020-02-15 16:43:32')
OfficerCheckIn.create_or_find_by(officer_id: '20', event_id: '20', check_in_date: '2020-02-14 16:36:54')
OfficerCheckIn.create_or_find_by(officer_id: '19', event_id: '2', check_in_date: '2020-03-15 15:27:53')
OfficerCheckIn.create_or_find_by(officer_id: '3', event_id: '9', check_in_date: '2020-01-19 17:32:25')
OfficerCheckIn.create_or_find_by(officer_id: '7', event_id: '19', check_in_date: '2020-02-22 17:13:43')
OfficerCheckIn.create_or_find_by(officer_id: '5', event_id: '12', check_in_date: '2020-02-29 18:41:36')
OfficerCheckIn.create_or_find_by(officer_id: '15', event_id: '3', check_in_date: '2020-01-30 15:25:53')
OfficerCheckIn.create_or_find_by(officer_id: '16', event_id: '6', check_in_date: '2020-03-25 17:37:43')
OfficerCheckIn.create_or_find_by(officer_id: '6', event_id: '7', check_in_date: '2020-03-31 16:15:42')
OfficerCheckIn.create_or_find_by(officer_id: '11', event_id: '4', check_in_date: '2020-02-20 16:57:24')
OfficerCheckIn.create_or_find_by(officer_id: '9', event_id: '15', check_in_date: '2020-02-28 14:58:53')
OfficerCheckIn.create_or_find_by(officer_id: '10', event_id: '10', check_in_date: '2020-01-11 16:03:33')
OfficerCheckIn.create_or_find_by(officer_id: '12', event_id: '13', check_in_date: '2020-01-15 15:45:03')
OfficerCheckIn.create_or_find_by(officer_id: '14', event_id: '14', check_in_date: '2020-02-28 17:24:56')
OfficerCheckIn.create_or_find_by(officer_id: '13', event_id: '5', check_in_date: '2020-03-14 15:54:46')
#Coordinator_Status Table
CoordinatorStatus.create_or_find_by(status: "Active", description: "This coordinator is active")
CoordinatorStatus.create_or_find_by(status: "Inactive", description: "This coordinator is inactive")
CoordinatorStatus.create_or_find_by(status: "Relieved", description: "This coordinator was relieved of their duties")
#Coordinator_Position Table
CoordinatorPosition.create_or_find_by(position: "Event Coordinator", description: "The event coordinator of AITP")
CoordinatorPosition.create_or_find_by(position: "Webmaster", description: "The website developer of AITP")
CoordinatorPosition.create_or_find_by(position: "Social Media Coordinator", description: "Handles social media accounts and posts regarding AITP")
CoordinatorPosition.create_or_find_by(position: "Outreach Coordinator", description: "Reaches out to external personnel for AITP")
#Coordinator Table
Coordinator.create_or_find_by(peoplesoft_id: '1422118', coordinator_position_id: '1', first_name: 'Liliana', middle_initial: 'A', last_name: 'Mason', date_of_birth: '1999-10-04', address: '234 Confession Lane', city: 'Houston', zip: '77834', state_id: '1', country_id: '1', home_phone: '713-084-8261', mobile_phone: '832-946-2736', coordinator_status_id: '1', payment: 'true', student_class_id: '4', major: 'CIS')
Coordinator.create_or_find_by(peoplesoft_id: '1443631', coordinator_position_id: '4', first_name: 'Eduardo', middle_initial: 'E', last_name: 'Brown', date_of_birth: '1998-04-12', address: '22823 Ladybug Street', city: 'Houston', zip: '79333', state_id: '1', country_id: '1', home_phone: '713-069-3751', mobile_phone: '832-395-7382', coordinator_status_id: '1', payment: 'true', student_class_id: '3', major: 'MIS')
Coordinator.create_or_find_by(peoplesoft_id: '1488579', coordinator_position_id: '3', first_name: 'Nayeli', middle_initial: 'C', last_name: 'Osorio', date_of_birth: '1997-02-10', address: '987 River Lane', city: 'Katy', zip: '78594', state_id: '1', country_id: '1', home_phone: '', mobile_phone: '713-204-7383', coordinator_status_id: '1', payment: 'true', student_class_id: '1', major: 'CIS')
Coordinator.create_or_find_by(peoplesoft_id: '1449458', coordinator_position_id: '1', first_name: 'Morgan', middle_initial: '', last_name: 'Livingston', date_of_birth: '1998-07-03', address: '356 String Lane', city: 'Houston', zip: '77233', state_id: '1', country_id: '1', home_phone: '281-048-5764', mobile_phone: '281-294-6284', coordinator_status_id: '2', payment: 'false', student_class_id: '2', major: 'CIS')
Coordinator.create_or_find_by(peoplesoft_id: '1446075', coordinator_position_id: '2', first_name: 'Ezequiel', middle_initial: 'E', last_name: 'Grass', date_of_birth: '1996-05-13', address: '542 Smiley Trail', city: 'Houston', zip: '77235', state_id: '1', country_id: '1', home_phone: '', mobile_phone: '713-029-4727', coordinator_status_id: '1', payment: 'true', student_class_id: '2', major: 'CIS')
Coordinator.create_or_find_by(peoplesoft_id: '1442856', coordinator_position_id: '3', first_name: 'Raul', middle_initial: 'C', last_name: 'Flores', date_of_birth: '1995-12-24', address: '232 Casper Lane', city: 'Woodlands', zip: '77383', state_id: '1', country_id: '1', home_phone: '713-495-9684', mobile_phone: '281-294-0284', coordinator_status_id: '2', payment: 'false', student_class_id: '4', major: 'MIS')
Coordinator.create_or_find_by(peoplesoft_id: '1495979', coordinator_position_id: '2', first_name: 'Erika', middle_initial: 'W', last_name: 'Mavris', date_of_birth: '1998-11-11', address: '1234 Mist Road', city: 'Houston', zip: '79323', state_id: '1', country_id: '1', home_phone: '', mobile_phone: '713-029-4782', coordinator_status_id: '2', payment: 'false', student_class_id: '3', major: 'CIS')
Coordinator.create_or_find_by(peoplesoft_id: '1485473', coordinator_position_id: '1', first_name: 'Shawn', middle_initial: '', last_name: 'Lewis', date_of_birth: '1996-02-11', address: '237 Winners Court', city: 'Pearland', zip: '77283', state_id: '1', country_id: '1', home_phone: '281-204-6485', mobile_phone: '832-405-8375', coordinator_status_id: '1', payment: 'true', student_class_id: '3', major: 'CIS')
Coordinator.create_or_find_by(peoplesoft_id: '1482254', coordinator_position_id: '4', first_name: 'Julia', middle_initial: 'P', last_name: 'Bew', date_of_birth: '1999-04-10', address: '2348 Education Lane', city: 'Houston', zip: '77346', state_id: '1', country_id: '1', home_phone: '', mobile_phone: '281-029-4736', coordinator_status_id: '1', payment: 'true', student_class_id: '2', major: 'CIS')
Coordinator.create_or_find_by(peoplesoft_id: '1482254', coordinator_position_id: '3', first_name: 'Jerry', middle_initial: 'R', last_name: 'Nao', date_of_birth: '1997-06-23', address: '8237 Skinner Road', city: 'Houston', zip: '79892', state_id: '1', country_id: '1', home_phone: '281-009-3947', mobile_phone: '713-229-4857', coordinator_status_id: '1', payment: 'true', student_class_id: '3', major: 'CIS')
#Coordinator_Check_In Table
CoordinatorCheckIn.create_or_find_by(coordinator_id: '7', event_id: '2', check_in_date: '2020-01-13 15:53:11')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '2', event_id: '5', check_in_date: '2020-04-01 16:11:22')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '4', event_id: '7', check_in_date: '2020-04-07 17:32:53')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '6', event_id: '6', check_in_date: '2020-03-15 14:24:54')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '1', event_id: '1', check_in_date: '2020-02-28 15:43:23')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '3', event_id: '10', check_in_date: '2020-01-21 16:21:31')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '8', event_id: '12', check_in_date: '2020-01-30 16:32:43')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '9', event_id: '11', check_in_date: '2020-02-01 15:03:32')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '10', event_id: '17', check_in_date: '2020-01-12 17:25:41')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '5', event_id: '4', check_in_date: '2020-04-01 17:43:43')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '2', event_id: '9', check_in_date: '2020-03-19 16:14:13')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '6', event_id: '20', check_in_date: '2020-02-21 15:33:56')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '3', event_id: '21', check_in_date: '2020-02-14 15:43:59')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '1', event_id: '8', check_in_date: '2020-01-10 16:24:27')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '7', event_id: '3', check_in_date: '2020-01-03 17:08:43')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '8', event_id: '19', check_in_date: '2020-02-27 14:57:54')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '1', event_id: '13', check_in_date: '2020-03-20 15:36:10')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '9', event_id: '14', check_in_date: '2020-03-28 16:27:42')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '4', event_id: '15', check_in_date: '2020-02-13 17:03:21')
CoordinatorCheckIn.create_or_find_by(coordinator_id: '10', event_id: '5', check_in_date: '2020-01-15 15:24:53')
